name: python

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/app_python.yaml'

defaults:
  run:
    working-directory: app_python

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [docs, code]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest