name: app_python

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/.python.yaml'

defaults:
  run:
    working-directory: app_python

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "app_python"

      - name: Test with pytest
        env:
          VISITS_FILE: ${{ github.workspace }}/app_python/visits.txt
        run: |
          pytest
